#!/usr/bin/env groovy

node {
    bitbucketStatusNotify(buildState: 'INPROGRESS') 
    stages {
        stage('Checkout source code') {
        	cleanWs()
                checkout scm
                 
        }
    }
}

